-- BD0901-ChavesEUuidV7.sql
-- PostgreSQL: Tipos de Chave Primaria, SERIAL, IDENTITY e UUID v7
-- UA3 - Aula 09 - Modelagem Logica/Fisica e Tipos de Chave

-- ============================================================
-- PARTE 1: SERIAL / BIGSERIAL (atalho classico)
-- ============================================================

CREATE TABLE cliente_serial (
    cliente_id   SERIAL PRIMARY KEY,
    nome         VARCHAR(200) NOT NULL,
    email        VARCHAR(200),
    data_cadastro DATE DEFAULT CURRENT_DATE
);

INSERT INTO cliente_serial (nome, email) VALUES ('Maria Silva', 'maria@email.com');
INSERT INTO cliente_serial (nome, email) VALUES ('Joao Souza', 'joao@email.com');
INSERT INTO cliente_serial (nome, email) VALUES ('Ana Costa', 'ana@email.com');

-- Ver a sequence criada implicitamente
SELECT pg_get_serial_sequence('cliente_serial', 'cliente_id');

-- ============================================================
-- PARTE 2: GENERATED AS IDENTITY (padrao SQL, recomendado)
-- ============================================================

-- Opcao A: GENERATED ALWAYS (nao permite override)
CREATE TABLE cliente_identity_always (
    cliente_id   INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(200) NOT NULL,
    email        VARCHAR(200),
    data_cadastro DATE DEFAULT CURRENT_DATE
);

-- Opcao B: GENERATED BY DEFAULT (permite override em migracoes)
CREATE TABLE cliente_identity_default (
    cliente_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR(200) NOT NULL,
    email        VARCHAR(200),
    data_cadastro DATE DEFAULT CURRENT_DATE
);

INSERT INTO cliente_identity_always (nome, email) VALUES ('Pedro Alves', 'pedro@email.com');
INSERT INTO cliente_identity_default (nome, email) VALUES ('Carla Mendes', 'carla@email.com');

-- ============================================================
-- PARTE 3: UUID V4 (gen_random_uuid)
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE cliente_uuid_v4 (
    cliente_id   UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    nome         VARCHAR(200) NOT NULL,
    email        VARCHAR(200),
    data_cadastro DATE DEFAULT CURRENT_DATE
);

INSERT INTO cliente_uuid_v4 (nome, email) VALUES ('Roberto Lima', 'roberto@email.com');
INSERT INTO cliente_uuid_v4 (nome, email) VALUES ('Fernanda Rocha', 'fernanda@email.com');

SELECT * FROM cliente_uuid_v4;

-- ============================================================
-- PARTE 4: UUID V7 (funcao PL/pgSQL ou via aplicacao)
-- ============================================================

-- Funcao uuid_v7() em PL/pgSQL
CREATE OR REPLACE FUNCTION uuid_v7() RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
    v_time_ms  BIGINT;
    v_rand_a   SMALLINT;
    v_rand_b   BIGINT;
BEGIN
    v_time_ms := (EXTRACT(EPOCH FROM clock_timestamp()) * 1000)::BIGINT;
    v_rand_a := (random() * 4096)::INT;  -- 12 bits
    v_rand_b := ((random() * 2^62)::BIGINT) | (10::BIGINT << 62);  -- variant 10xx

    -- Monta UUID: [timestamp 48 bits][version=7 4 bits][rand_a 12 bits]
    --              [variant 2 bits][rand_b 62 bits]
    RETURN encode(
        set_byte(
            set_byte(
                set_byte(
                    set_byte(
                        set_byte(
                            set_byte(
                                set_byte(
                                    set_byte(
                                        '\x00000000000000000000000000000000'::BYTEA,
                                        0, (v_time_ms >> 40)::INT & 255),
                                        1, (v_time_ms >> 32)::INT & 255),
                                        2, (v_time_ms >> 24)::INT & 255),
                                        3, (v_time_ms >> 16)::INT & 255),
                                    4, (v_time_ms >> 8)::INT & 255),
                                5, v_time_ms::INT & 255),
                            6, ((7 << 4) | (v_rand_a >> 8)) & 255),
                        7, v_rand_a & 255),
            'hex'
    )::UUID;
END;
$$;

-- Tabela com UUID v7
CREATE TABLE cliente_uuid_v7 (
    cliente_id   UUID DEFAULT uuid_v7() PRIMARY KEY,
    nome         VARCHAR(200) NOT NULL,
    email        VARCHAR(200),
    data_cadastro DATE DEFAULT CURRENT_DATE
);

INSERT INTO cliente_uuid_v7 (nome, email) VALUES ('Lucas Amaral', 'lucas@email.com');
INSERT INTO cliente_uuid_v7 (nome, email) VALUES ('Beatriz Santos', 'beatriz@email.com');
INSERT INTO cliente_uuid_v7 (nome, email) VALUES ('Gabriel Oliveira', 'gabriel@email.com');

SELECT * FROM cliente_uuid_v7 ORDER BY cliente_id;

-- Extrair timestamp de UUID v7 (aproximado)
SELECT cliente_id,
       ('x' || REPLACE(cliente_id::TEXT, '-', ''))::BIT(48)::BIGINT AS timestamp_approx
  FROM cliente_uuid_v7;

-- ============================================================
-- PARTE 5: COMPARACAO DE TAMANHO DE INDICES
-- ============================================================

SELECT
    relname AS tabela,
    pg_size_pretty(pg_relation_size(relid)) AS tamanho_tabela,
    pg_size_pretty(pg_indexes_size(relid)) AS tamanho_indices
  FROM pg_stat_user_tables
 WHERE relname LIKE 'cliente%'
 ORDER BY relname;

-- Ou via pg_class
SELECT
    c.relname AS tabela,
    pg_size_pretty(pg_table_size(c.oid)) AS tamanho_dados,
    pg_size_pretty(pg_indexes_size(c.oid)) AS tamanho_indices
  FROM pg_class c
 WHERE c.relname LIKE 'cliente%'
   AND c.relkind = 'r'
 ORDER BY c.relname;
