-- BD3201-ProjetoFinal.sql
-- Oracle: Projeto Integrador Final - Sistema de Biblioteca
-- UA12 - Aula 32

-- ============================================================
-- DDL
-- ============================================================
CREATE TABLE editora (
    editora_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR2(200) NOT NULL
);

CREATE TABLE livro (
    livro_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn       VARCHAR2(17) UNIQUE NOT NULL,
    titulo     VARCHAR2(300) NOT NULL,
    editora_id NUMBER NOT NULL,
    ano        NUMBER(4),
    edicao     NUMBER(2),
    CONSTRAINT fk_livro_editora FOREIGN KEY (editora_id)
        REFERENCES editora (editora_id)
);

CREATE TABLE autor (
    autor_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(200) NOT NULL,
    nacionalidade VARCHAR2(100)
);

CREATE TABLE livro_autor (
    livro_id NUMBER NOT NULL,
    autor_id NUMBER NOT NULL,
    PRIMARY KEY (livro_id, autor_id),
    CONSTRAINT fk_la_livro FOREIGN KEY (livro_id) REFERENCES livro (livro_id),
    CONSTRAINT fk_la_autor FOREIGN KEY (autor_id) REFERENCES autor (autor_id)
);

CREATE TABLE usuario (
    usuario_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula  VARCHAR2(20) UNIQUE NOT NULL,
    nome       VARCHAR2(200) NOT NULL,
    email      VARCHAR2(200) UNIQUE NOT NULL,
    tipo       VARCHAR2(20) DEFAULT 'ALUNO' CHECK (tipo IN ('ALUNO', 'PROFESSOR'))
);

CREATE TABLE emprestimo (
    emprestimo_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id     NUMBER NOT NULL,
    livro_id       NUMBER NOT NULL,
    data_retirada  DATE DEFAULT SYSDATE NOT NULL,
    data_prevista  DATE NOT NULL,
    data_devolucao DATE,
    multa          NUMBER(10,2) DEFAULT 0,
    CONSTRAINT fk_emp_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (usuario_id),
    CONSTRAINT fk_emp_livro FOREIGN KEY (livro_id)
        REFERENCES livro (livro_id)
);

-- Indices
CREATE INDEX idx_emp_usuario ON emprestimo(usuario_id);
CREATE INDEX idx_emp_livro ON emprestimo(livro_id);
CREATE INDEX idx_livro_titulo ON livro(titulo);

-- ============================================================
-- AUDITORIA
-- ============================================================
CREATE TABLE auditoria_emprestimo (
    id_auditoria  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacao      VARCHAR2(10),
    emprestimo_id NUMBER,
    data_hora     TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE OR REPLACE TRIGGER trg_auditoria_emprestimo
    AFTER INSERT OR UPDATE ON emprestimo
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_emprestimo (operacao, emprestimo_id)
        VALUES ('INSERT', :NEW.emprestimo_id);
    ELSIF UPDATING THEN
        INSERT INTO auditoria_emprestimo (operacao, emprestimo_id)
        VALUES ('UPDATE', :NEW.emprestimo_id);
    END IF;
END;
/

-- ============================================================
-- PROCEDURES
-- ============================================================
CREATE OR REPLACE PROCEDURE realizar_emprestimo (
    p_usuario_id IN NUMBER,
    p_livro_id   IN NUMBER
) IS
BEGIN
    INSERT INTO emprestimo (usuario_id, livro_id, data_prevista)
    VALUES (p_usuario_id, p_livro_id, SYSDATE + 14);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE devolver_livro (
    p_emprestimo_id IN NUMBER
) IS
    v_data_prevista DATE;
    v_dias_atraso   NUMBER;
BEGIN
    UPDATE emprestimo SET data_devolucao = SYSDATE
     WHERE emprestimo_id = p_emprestimo_id
       AND data_devolucao IS NULL;

    SELECT data_prevista INTO v_data_prevista
      FROM emprestimo WHERE emprestimo_id = p_emprestimo_id;

    v_dias_atraso := TRUNC(SYSDATE) - TRUNC(v_data_prevista);
    IF v_dias_atraso > 0 THEN
        UPDATE emprestimo SET multa = v_dias_atraso * 2.00
         WHERE emprestimo_id = p_emprestimo_id;
    END IF;
    COMMIT;
END;
/
