-- BD2001-Triggers.sql
-- Oracle: Triggers de Auditoria e Validacao (PL/SQL)
-- UA7 - Aula 20 - Programacao no Banco de Dados

-- ============================================================
-- TABELA DE AUDITORIA
-- ============================================================
CREATE TABLE auditoria_professor (
    id_auditoria  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operacao      VARCHAR2(10),
    professor_id  NUMBER,
    nome_antigo   VARCHAR2(200),
    nome_novo     VARCHAR2(200),
    usuario_banco VARCHAR2(100),
    data_hora     TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- ============================================================
-- TRIGGER 1: Auditoria de Professor
-- ============================================================
CREATE OR REPLACE TRIGGER trg_auditoria_professor
    AFTER INSERT OR UPDATE OR DELETE ON professor
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_professor (operacao, professor_id, nome_novo, usuario_banco)
        VALUES ('INSERT', :NEW.professor_id, :NEW.nome, USER);
    ELSIF UPDATING THEN
        INSERT INTO auditoria_professor (operacao, professor_id, nome_antigo, nome_novo, usuario_banco)
        VALUES ('UPDATE', :NEW.professor_id, :OLD.nome, :NEW.nome, USER);
    ELSIF DELETING THEN
        INSERT INTO auditoria_professor (operacao, professor_id, nome_antigo, usuario_banco)
        VALUES ('DELETE', :OLD.professor_id, :OLD.nome, USER);
    END IF;
END;
/

-- ============================================================
-- TRIGGER 2: Preenchimento automatico de data
-- ============================================================
ALTER TABLE produto ADD data_atualizacao DATE;

CREATE OR REPLACE TRIGGER trg_set_data_atualizacao
    BEFORE INSERT OR UPDATE ON produto
    FOR EACH ROW
BEGIN
    :NEW.data_atualizacao := SYSDATE;
END;
/

-- ============================================================
-- TRIGGER 3: Validacao de regra de negocio
-- ============================================================
CREATE OR REPLACE TRIGGER trg_valida_turma_datas
    BEFORE INSERT OR UPDATE ON turma
    FOR EACH ROW
BEGIN
    IF :NEW.data_final < :NEW.data_inicial THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Data final nao pode ser anterior a data inicial');
    END IF;
END;
/

-- ============================================================
-- TESTES
-- ============================================================
-- Teste auditoria
INSERT INTO professor (nome, cpf) VALUES ('Teste Trigger', '111.111.111-11');
UPDATE professor SET nome = 'Teste Trigger Atualizado' WHERE cpf = '111.111.111-11';
DELETE FROM professor WHERE cpf = '111.111.111-11';
SELECT * FROM auditoria_professor ORDER BY id_auditoria;

-- Teste validacao (deve falhar)
INSERT INTO turma (horario, duracao, data_inicial, data_final, professor_id, curso_id)
VALUES ('19:00', 3, DATE '2026-12-01', DATE '2026-01-01', 1, 1);
-- ORA-20001: Data final nao pode ser anterior a data inicial
