-- =============================================================================
-- BD1301-DQL.sql
-- Aula 13 - DQL Basico: SELECT, WHERE, ORDER BY e funcoes de data/string (Oracle)
-- Estudo de caso: BookHub - livraria online
-- Prof. Giovane Barcelos
-- =============================================================================
-- Script autocontido: recria o esquema BookHub e demonstra os fundamentos de DQL.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. LIMPEZA E RECRIACAO DO ESQUEMA (ver detalhes/comentarios em BD1201-DML.sql)
-- -----------------------------------------------------------------------------
BEGIN
   FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('ITEMVENDA','VENDA','ESTOQUE','LIVROESTOQUESTAGING',
                                   'LIVRO','CLIENTE','AUTOR'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

CREATE TABLE Autor (
    autor_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(150) NOT NULL,
    nacionalidade   VARCHAR2(60)  NOT NULL,
    data_nascimento DATE          NOT NULL
);

CREATE TABLE Livro (
    livro_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor_id        NUMBER        NOT NULL REFERENCES Autor (autor_id),
    titulo          VARCHAR2(200) NOT NULL,
    genero          VARCHAR2(60)  NOT NULL,
    preco           NUMBER(10,2)  NOT NULL,
    tipo            CHAR(1)       NOT NULL CHECK (tipo IN ('F','D')),
    ano_publicacao  NUMBER(4)     NOT NULL
);

CREATE TABLE Cliente (
    cliente_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(150) NOT NULL,
    email           VARCHAR2(150) NOT NULL UNIQUE,
    telefone        VARCHAR2(30)  NOT NULL,
    data_cadastro   DATE          NOT NULL
);

CREATE TABLE Venda (
    venda_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda      DATE          NOT NULL,
    forma_pagamento VARCHAR2(30)  NOT NULL,
    valor_total     NUMBER(10,2)  NOT NULL,
    cliente_id      NUMBER        NOT NULL REFERENCES Cliente (cliente_id)
);

CREATE TABLE ItemVenda (
    itemvenda_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id        NUMBER        NOT NULL REFERENCES Venda (venda_id),
    livro_id        NUMBER        NOT NULL REFERENCES Livro (livro_id),
    preco_unitario  NUMBER(10,2)  NOT NULL,
    quantidade      NUMBER(6)     NOT NULL
);

INSERT INTO Autor (nome, nacionalidade, data_nascimento) VALUES ('Dick Vigarista', 'Brasil', DATE '1978-05-12');
INSERT INTO Autor (nome, nacionalidade, data_nascimento) VALUES ('Penelope Charmosa', 'Reino Unido', DATE '1965-11-02');
INSERT INTO Autor (nome, nacionalidade, data_nascimento) VALUES ('Muttley', 'Estados Unidos', DATE '1985-07-20');
INSERT INTO Autor (nome, nacionalidade, data_nascimento) VALUES ('Aurora Beltrame', 'Portugal', DATE '1990-03-15');

INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (1, 'Programacao em Java - Avancado', 'Tecnologia', 120.00, 'F', 2019);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (1, 'Introducao ao SQL', 'Tecnologia', 45.00, 'F', 2015);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (2, 'Romance das Estacoes', 'Ficcao', 35.50, 'D', 2021);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (3, 'Historias do Oriente', 'Ficcao', 55.00, 'F', 1998);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (2, 'Aplicacoes em Rust', 'Tecnologia', 89.90, 'D', 2022);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (3, 'Contos de Inverno', 'Ficcao', 29.90, 'D', 2020);
INSERT INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao) VALUES (1, 'Banco de Dados Essencial', 'Tecnologia', 99.00, 'F', 2023);

INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES ('Ze Bugadinho', 'ze.bugadinho@email.com', '+55-11-99999-0001', DATE '2023-02-10');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES ('Ana Stackoverflow', 'ana.stackoverflow@email.com', '+55-21-98888-1111', DATE '2022-11-05');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES ('Beto Nullpointer', 'beto.nullpointer@email.com', '+55-41-97777-2222', DATE '2024-01-03');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES ('Carla Datasteria', NULL, '+55-51-96666-3333', DATE '2024-06-20');
-- Observacao: o email de Carla foi deixado NULL de proposito, para demonstrar
-- NVL/COALESCE mais adiante. Isso exige remover a constraint NOT NULL/UNIQUE
-- de forma pontual neste script de estudo (em producao, email seria obrigatorio).
ALTER TABLE Cliente MODIFY (email NULL);

INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES (DATE '2025-08-10', 'Cartao', 165.00, 1);
INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES (DATE '2025-08-12', 'Boleto', 160.90, 2);
INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES (DATE '2025-09-01', 'Pix', 99.00, 3);

INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (1, 1, 120.00, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (1, 2, 45.00, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (2, 3, 35.50, 2);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (2, 5, 89.90, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (3, 7, 99.00, 1);

COMMIT;

-- -----------------------------------------------------------------------------
-- 1. SELECT basico
-- -----------------------------------------------------------------------------
-- 1.1 Todas as colunas
SELECT * FROM Livro;

-- 1.2 Projecao de colunas especificas com alias
SELECT titulo AS titulo_livro, preco, tipo FROM Livro;

-- 1.3 Coluna calculada (expressao aritmetica no SELECT)
SELECT titulo, preco, ROUND(preco * 0.9, 2) AS preco_com_desconto FROM Livro;

-- -----------------------------------------------------------------------------
-- 2. WHERE - filtros
-- -----------------------------------------------------------------------------
-- 2.1 Igualdade e comparacao numerica
SELECT titulo, preco FROM Livro WHERE tipo = 'D';
SELECT titulo, preco FROM Livro WHERE preco > 50;

-- 2.2 Operadores logicos combinados
SELECT titulo, genero, preco FROM Livro
 WHERE genero = 'Tecnologia' AND preco BETWEEN 40 AND 100;

-- 2.3 IN, LIKE e IS NULL
SELECT titulo FROM Livro WHERE genero IN ('Ficcao', 'Tecnologia');
SELECT titulo FROM Livro WHERE titulo LIKE '%SQL%';
SELECT nome, email FROM Cliente WHERE email IS NULL;

-- -----------------------------------------------------------------------------
-- 3. ORDER BY
-- -----------------------------------------------------------------------------
SELECT titulo, preco FROM Livro ORDER BY preco DESC;
SELECT titulo, genero, preco FROM Livro ORDER BY genero ASC, preco DESC;

-- -----------------------------------------------------------------------------
-- 4. Funcoes de data (Oracle: SYSDATE, TO_CHAR, ADD_MONTHS, MONTHS_BETWEEN)
-- -----------------------------------------------------------------------------
-- 4.1 Data/hora atual do servidor
SELECT SYSDATE AS agora FROM dual;

-- 4.2 Formatando datas com TO_CHAR
SELECT nome,
       TO_CHAR(data_cadastro, 'DD/MM/YYYY') AS cadastro_br,
       TO_CHAR(data_cadastro, 'YYYY-MM') AS ano_mes
  FROM Cliente;

-- 4.3 Tempo de casa do cliente (em dias e em meses)
SELECT nome,
       SYSDATE - data_cadastro AS dias_de_cadastro,
       TRUNC(MONTHS_BETWEEN(SYSDATE, data_cadastro)) AS meses_de_cadastro
  FROM Cliente;

-- 4.4 Ultimo dia do mes da venda e proximo mes
SELECT venda_id, data_venda,
       LAST_DAY(data_venda) AS fim_do_mes,
       ADD_MONTHS(data_venda, 1) AS mesmo_dia_mes_seguinte
  FROM Venda;

-- -----------------------------------------------------------------------------
-- 5. Funcoes de string (Oracle)
-- -----------------------------------------------------------------------------
SELECT UPPER(nome) AS nome_maiusculo, LOWER(nome) AS nome_minusculo FROM Cliente;
SELECT titulo, LENGTH(titulo) AS tamanho_titulo, SUBSTR(titulo, 1, 10) AS resumo FROM Livro;
SELECT nome, telefone, REPLACE(telefone, '-', '') AS telefone_sem_traco FROM Cliente;
SELECT nome || ' <' || NVL(email, 'sem-email@bookhub.com') || '>' AS contato FROM Cliente;

-- -----------------------------------------------------------------------------
-- 6. Tratamento de nulos: NVL (Oracle)
-- -----------------------------------------------------------------------------
-- NVL(expr, valor_se_nulo): retorna valor_se_nulo quando expr for NULL
SELECT nome, NVL(email, 'Nao informado') AS email_ou_padrao FROM Cliente;

-- NVL2(expr, valor_se_nao_nulo, valor_se_nulo): variante Oracle com 2 saidas
SELECT nome, NVL2(email, 'Possui email', 'Sem email') AS status_email FROM Cliente;

-- COALESCE tambem existe no Oracle (padrao ANSI) e aceita N argumentos
SELECT nome, COALESCE(email, telefone, 'Sem contato') AS contato_preferencial FROM Cliente;

-- =============================================================================
-- Fim do script. Equivalente PostgreSQL: repository/class13/postgresql/BD1301-DQL.sql
-- =============================================================================
