-- BD1701-Integridade.sql
-- Oracle: Integridade Referencial e Boas Praticas
-- UA6 - Aula 17 - Normalizacao e Integridade Referencial

-- ============================================================
-- PARTE 1: CASCADE (entidade fraca)
-- ============================================================
-- Recriar ausencia com ON DELETE CASCADE
DROP TABLE ausencia CASCADE CONSTRAINTS;
CREATE TABLE ausencia (
    ausencia_id  NUMBER NOT NULL,
    matricula_id NUMBER NOT NULL,
    data         DATE NOT NULL,
    CONSTRAINT pk_ausencia PRIMARY KEY (matricula_id, ausencia_id),
    CONSTRAINT fk_ausencia_matricula FOREIGN KEY (matricula_id)
        REFERENCES matricula (matricula_id) ON DELETE CASCADE
);

-- ============================================================
-- PARTE 2: CHECK constraints
-- ============================================================
ALTER TABLE aluno ADD CONSTRAINT ck_aluno_altura CHECK (altura > 0 AND altura < 3.0);
ALTER TABLE aluno ADD CONSTRAINT ck_aluno_peso CHECK (peso > 0 AND peso < 500);
ALTER TABLE turma ADD CONSTRAINT ck_turma_datas CHECK (data_final >= data_inicial);

-- CHECK com enum-like
ALTER TABLE professor ADD CONSTRAINT ck_titulacao CHECK (
    titulacao IN ('Graduacao', 'Especializacao', 'Mestrado', 'Doutorado'));

-- ============================================================
-- PARTE 3: FK com nome explicito + indice
-- ============================================================
ALTER TABLE turma ADD CONSTRAINT fk_turma_professor
    FOREIGN KEY (professor_id) REFERENCES professor (professor_id)
    ON DELETE RESTRICT;

ALTER TABLE turma ADD CONSTRAINT fk_turma_curso
    FOREIGN KEY (curso_id) REFERENCES curso (curso_id)
    ON DELETE RESTRICT;

-- Indices em FKs (Oracle nao cria automaticamente!)
CREATE INDEX idx_turma_professor ON turma(professor_id);
CREATE INDEX idx_turma_curso ON turma(curso_id);
CREATE INDEX idx_matricula_turma ON matricula(turma_id);
CREATE INDEX idx_matricula_aluno ON matricula(aluno_id);
CREATE INDEX idx_telefone_professor ON telefone(professor_id);

-- ============================================================
-- PARTE 4: TESTANDO RESTRICT vs CASCADE
-- ============================================================
-- Tentar deletar professor que tem turma (RESTRICT deve bloquear)
DELETE FROM professor WHERE professor_id = 1;
-- ORA-02292: integrity constraint violated - child record found

-- Deletar matricula com CASCADE (ausencias sao removidas)
SELECT COUNT(*) FROM ausencia WHERE matricula_id = 1;  -- X ausencias
DELETE FROM matricula WHERE matricula_id = 1;
SELECT COUNT(*) FROM ausencia WHERE matricula_id = 1;  -- 0

-- ============================================================
-- PARTE 5: Exemplo completo com todas as constraints
-- ============================================================
CREATE TABLE pedido (
    pedido_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  NUMBER NOT NULL,
    data_pedido DATE DEFAULT SYSDATE NOT NULL,
    valor_total NUMBER(10,2) NOT NULL,
    status      VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id)
        REFERENCES cliente (cliente_id) ON DELETE RESTRICT,
    CONSTRAINT ck_pedido_valor CHECK (valor_total > 0),
    CONSTRAINT ck_pedido_status CHECK (status IN (
        'PENDENTE', 'CONFIRMADO', 'ENVIADO', 'ENTREGUE', 'CANCELADO'))
);

CREATE INDEX idx_pedido_cliente ON pedido(cliente_id);
