-- =============================================================================
-- BD1201-DML.sql
-- Aula 12 - DML: INSERT / UPDATE / DELETE / MERGE (Oracle Database)
-- Estudo de caso: BookHub - livraria online
-- Prof. Giovane Barcelos
-- =============================================================================
-- Este script e autocontido: recria o esquema BookHub (6 tabelas), popula com
-- dados de exemplo e demonstra os quatro comandos DML centrais desta aula.
-- Execute em um schema Oracle vazio (ou rode a secao 0 para limpar antes).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. LIMPEZA (idempotencia ao reexecutar o script)
-- -----------------------------------------------------------------------------
BEGIN
   FOR t IN (SELECT table_name FROM user_tables
             WHERE table_name IN ('ITEMVENDA','VENDA','ESTOQUE','LIVROESTOQUESTAGING',
                                   'LIVRO','CLIENTE','AUTOR'))
   LOOP
      EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
   END LOOP;
END;
/

-- -----------------------------------------------------------------------------
-- 1. ESQUEMA BOOKHUB
-- -----------------------------------------------------------------------------
CREATE TABLE Autor (
    autor_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(150) NOT NULL,
    nacionalidade   VARCHAR2(60)  NOT NULL,
    data_nascimento DATE          NOT NULL
);

CREATE TABLE Livro (
    livro_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autor_id        NUMBER        NOT NULL,
    titulo          VARCHAR2(200) NOT NULL,
    genero          VARCHAR2(60)  NOT NULL,
    preco           NUMBER(10,2)  NOT NULL,
    tipo            CHAR(1)       NOT NULL CHECK (tipo IN ('F','D')), -- F=Fisico, D=Digital
    ano_publicacao  NUMBER(4)     NOT NULL,
    CONSTRAINT autor_livro_fk FOREIGN KEY (autor_id) REFERENCES Autor (autor_id)
);

CREATE TABLE Cliente (
    cliente_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR2(150) NOT NULL,
    email           VARCHAR2(150) NOT NULL UNIQUE,
    telefone        VARCHAR2(30)  NOT NULL,
    data_cadastro   DATE          NOT NULL
);

CREATE TABLE Venda (
    venda_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_venda      DATE          NOT NULL,
    forma_pagamento VARCHAR2(30)  NOT NULL,
    valor_total     NUMBER(10,2)  NOT NULL,
    cliente_id      NUMBER        NOT NULL,
    CONSTRAINT cliente_venda_fk FOREIGN KEY (cliente_id) REFERENCES Cliente (cliente_id)
);

CREATE TABLE ItemVenda (
    itemvenda_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venda_id        NUMBER        NOT NULL,
    livro_id        NUMBER        NOT NULL,
    preco_unitario  NUMBER(10,2)  NOT NULL,
    quantidade      NUMBER(6)     NOT NULL,
    CONSTRAINT venda_itemvenda_fk FOREIGN KEY (venda_id) REFERENCES Venda (venda_id),
    CONSTRAINT livro_itemvenda_fk FOREIGN KEY (livro_id) REFERENCES Livro (livro_id)
);

-- Tabela de estoque, usada nos exemplos de MERGE (upsert) mais adiante
CREATE TABLE Estoque (
    livro_id             NUMBER PRIMARY KEY,
    quantidade_disponivel NUMBER(8) NOT NULL,
    ultima_atualizacao    DATE     NOT NULL,
    CONSTRAINT livro_estoque_fk FOREIGN KEY (livro_id) REFERENCES Livro (livro_id)
);

-- Tabela de staging: simula um arquivo/feed do fornecedor com contagens novas de
-- estoque, algumas para livros ja cadastrados em Estoque, outras para livros novos
CREATE TABLE LivroEstoqueStaging (
    livro_id        NUMBER PRIMARY KEY,
    quantidade_nova NUMBER(8) NOT NULL
);

-- -----------------------------------------------------------------------------
-- 2. INSERT - carga inicial de dados
-- -----------------------------------------------------------------------------
-- 2.1 INSERT simples (uma linha por vez)
INSERT INTO Autor (nome, nacionalidade, data_nascimento)
VALUES ('Dick Vigarista', 'Brasil', DATE '1978-05-12');

INSERT INTO Autor (nome, nacionalidade, data_nascimento)
VALUES ('Penelope Charmosa', 'Reino Unido', DATE '1965-11-02');

INSERT INTO Autor (nome, nacionalidade, data_nascimento)
VALUES ('Muttley', 'Estados Unidos', DATE '1985-07-20');

INSERT INTO Autor (nome, nacionalidade, data_nascimento)
VALUES ('Aurora Beltrame', 'Portugal', DATE '1990-03-15');

-- 2.2 INSERT ALL - multiplas linhas em um unico comando (sintaxe Oracle)
INSERT ALL
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (1, 'Programacao em Java - Avancado', 'Tecnologia', 120.00, 'F', 2019)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (1, 'Introducao ao SQL', 'Tecnologia', 45.00, 'F', 2015)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (2, 'Romance das Estacoes', 'Ficcao', 35.50, 'D', 2021)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (3, 'Historias do Oriente', 'Ficcao', 55.00, 'F', 1998)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (2, 'Aplicacoes em Rust', 'Tecnologia', 89.90, 'D', 2022)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (3, 'Contos de Inverno', 'Ficcao', 29.90, 'D', 2020)
    INTO Livro (autor_id, titulo, genero, preco, tipo, ano_publicacao)
         VALUES (1, 'Banco de Dados Essencial', 'Tecnologia', 99.00, 'F', 2023)
SELECT * FROM dual;

INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES
    ('Ze Bugadinho', 'ze.bugadinho@email.com', '+55-11-99999-0001', DATE '2023-02-10');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES
    ('Ana Stackoverflow', 'ana.stackoverflow@email.com', '+55-21-98888-1111', DATE '2022-11-05');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES
    ('Beto Nullpointer', 'beto.nullpointer@email.com', '+55-41-97777-2222', DATE '2024-01-03');
INSERT INTO Cliente (nome, email, telefone, data_cadastro) VALUES
    ('Carla Datasteria', 'carla.datasteria@email.com', '+55-51-96666-3333', DATE '2024-06-20');

INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES
    (DATE '2025-08-10', 'Cartao', 165.00, 1);
INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES
    (DATE '2025-08-12', 'Boleto', 160.90, 2);
INSERT INTO Venda (data_venda, forma_pagamento, valor_total, cliente_id) VALUES
    (DATE '2025-09-01', 'Pix', 99.00, 3);

INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (1, 1, 120.00, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (1, 2, 45.00, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (2, 3, 35.50, 2);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (2, 5, 89.90, 1);
INSERT INTO ItemVenda (venda_id, livro_id, preco_unitario, quantidade) VALUES (3, 7, 99.00, 1);

INSERT INTO Estoque (livro_id, quantidade_disponivel, ultima_atualizacao) VALUES (1, 12, DATE '2025-09-01');
INSERT INTO Estoque (livro_id, quantidade_disponivel, ultima_atualizacao) VALUES (2, 30, DATE '2025-09-01');
INSERT INTO Estoque (livro_id, quantidade_disponivel, ultima_atualizacao) VALUES (3, 5,  DATE '2025-09-01');
INSERT INTO Estoque (livro_id, quantidade_disponivel, ultima_atualizacao) VALUES (4, 0,  DATE '2025-09-01');

COMMIT;

-- -----------------------------------------------------------------------------
-- 3. UPDATE
-- -----------------------------------------------------------------------------
-- 3.1 UPDATE simples: reajuste de 10% em todos os livros fisicos
UPDATE Livro
   SET preco = ROUND(preco * 1.10, 2)
 WHERE tipo = 'F';

-- 3.2 UPDATE com subquery correlacionada: zera estoque de livros descontinuados
--     (ano de publicacao anterior a 2000)
UPDATE Estoque e
   SET quantidade_disponivel = 0
 WHERE EXISTS (SELECT 1 FROM Livro l
                WHERE l.livro_id = e.livro_id
                  AND l.ano_publicacao < 2000);

-- 3.3 UPDATE multi-coluna com CASE: reclassifica forma de pagamento em vendas
UPDATE Venda
   SET forma_pagamento = CASE
                            WHEN forma_pagamento = 'Boleto' THEN 'Boleto Bancario'
                            ELSE forma_pagamento
                          END
 WHERE forma_pagamento = 'Boleto';

COMMIT;

-- -----------------------------------------------------------------------------
-- 4. DELETE
-- -----------------------------------------------------------------------------
-- 4.1 DELETE simples: remove livros anteriores a 1990 (nenhum na carga atual,
--     mas ilustra o padrao antes de popular novos dados de teste)
DELETE FROM Livro WHERE ano_publicacao < 1990;

-- 4.2 DELETE com subquery: remove itens de estoque de livros sem nenhuma venda
--     registrada (demonstra cuidado com integridade referencial)
DELETE FROM Estoque e
 WHERE e.quantidade_disponivel = 0
   AND NOT EXISTS (SELECT 1 FROM ItemVenda iv WHERE iv.livro_id = e.livro_id);

ROLLBACK; -- desfeito propositalmente: mantemos os dados para os proximos passos

-- -----------------------------------------------------------------------------
-- 5. MERGE (upsert nativo do Oracle)
-- -----------------------------------------------------------------------------
-- Cenario: o fornecedor envia uma atualizacao de estoque (LivroEstoqueStaging).
-- Se o livro ja existe em Estoque, ATUALIZA a quantidade; senao, INSERE a linha.
INSERT INTO LivroEstoqueStaging (livro_id, quantidade_nova) VALUES (1, 8);   -- existe -> update
INSERT INTO LivroEstoqueStaging (livro_id, quantidade_nova) VALUES (3, 20);  -- existe -> update
INSERT INTO LivroEstoqueStaging (livro_id, quantidade_nova) VALUES (6, 15);  -- novo   -> insert
INSERT INTO LivroEstoqueStaging (livro_id, quantidade_nova) VALUES (7, 40);  -- novo   -> insert
COMMIT;

MERGE INTO Estoque tgt
USING LivroEstoqueStaging src
   ON (tgt.livro_id = src.livro_id)
WHEN MATCHED THEN
     UPDATE SET tgt.quantidade_disponivel = src.quantidade_nova,
                tgt.ultima_atualizacao    = SYSDATE
WHEN NOT MATCHED THEN
     INSERT (livro_id, quantidade_disponivel, ultima_atualizacao)
     VALUES (src.livro_id, src.quantidade_nova, SYSDATE);

COMMIT;

-- Conferindo o resultado do MERGE
SELECT livro_id, quantidade_disponivel, ultima_atualizacao FROM Estoque ORDER BY livro_id;

-- -----------------------------------------------------------------------------
-- 6. MERGE com condicao adicional de DELETE (recurso avancado do Oracle)
-- -----------------------------------------------------------------------------
-- Remove do estoque qualquer linha cuja quantidade recem-sincronizada seja zero
MERGE INTO Estoque tgt
USING (SELECT 5 AS livro_id, 0 AS quantidade_nova FROM dual) src
   ON (tgt.livro_id = src.livro_id)
WHEN MATCHED THEN
     UPDATE SET tgt.quantidade_disponivel = src.quantidade_nova
     DELETE WHERE tgt.quantidade_disponivel = 0
WHEN NOT MATCHED THEN
     INSERT (livro_id, quantidade_disponivel, ultima_atualizacao)
     VALUES (src.livro_id, src.quantidade_nova, SYSDATE);

COMMIT;

-- =============================================================================
-- Fim do script. Equivalente PostgreSQL: repository/class12/postgresql/BD1201-DML.sql
-- =============================================================================
