@startuml
' BD-19-CicloExecucaoPlPgSql.puml
' Visualizar em: https://plantuml.com/

start
:Chamada: SELECT função(...) ou CALL procedure(...);
:DECLARE (opcional): variáveis,\n%TYPE, %ROWTYPE, RECORD;
:BEGIN: comandos SQL e PL/pgSQL\nexecutados em sequência;
if (Ocorreu erro?) then (não)
  :Function: RETURN valor / RETURN QUERY\nProcedure: COMMIT (se aplicável);
else (sim)
  :EXCEPTION WHEN condição / WHEN OTHERS;
  :RAISE NOTICE / RAISE EXCEPTION\n+ ROLLBACK (em procedure);
endif
:END — controle retorna ao chamador;
stop
@enduml
