-- BD0901-ChavesEUuidV7.sql
-- Oracle: Tipos de Chave Primaria, SEQUENCE, IDENTITY e UUID v7
-- UA3 - Aula 09 - Modelagem Logica/Fisica e Tipos de Chave

-- ============================================================
-- PARTE 1: INTEGER COM IDENTITY
-- ============================================================

-- Opcao A: IDENTITY (Oracle 12c+)
CREATE TABLE cliente_seq (
    cliente_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome         VARCHAR2(200) NOT NULL,
    email        VARCHAR2(200),
    data_cadastro DATE DEFAULT SYSDATE
);

-- Testando insercao sem especificar ID
INSERT INTO cliente_seq (nome, email) VALUES ('Maria Silva', 'maria@email.com');
INSERT INTO cliente_seq (nome, email) VALUES ('Joao Souza', 'joao@email.com');
INSERT INTO cliente_seq (nome, email) VALUES ('Ana Costa', 'ana@email.com');

SELECT * FROM cliente_seq;

-- ============================================================
-- PARTE 2: SEQUENCE MANUAL (estilo Oracle tradicional)
-- ============================================================

CREATE SEQUENCE seq_produto START WITH 1000 INCREMENT BY 1;

CREATE TABLE produto_seq (
    produto_id NUMBER DEFAULT seq_produto.NEXTVAL PRIMARY KEY,
    descricao  VARCHAR2(300) NOT NULL,
    preco      NUMBER(10,2)
);

INSERT INTO produto_seq (descricao, preco) VALUES ('Notebook', 4500.00);
INSERT INTO produto_seq (descricao, preco) VALUES ('Monitor 27"', 1800.00);
INSERT INTO produto_seq (descricao, preco) VALUES ('Teclado Mecanico', 350.00);

SELECT * FROM produto_seq;

-- ============================================================
-- PARTE 3: UUID V4 (SYS_GUID)
-- ============================================================

CREATE TABLE cliente_uuid_v4 (
    cliente_id   RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    nome         VARCHAR2(200) NOT NULL,
    email        VARCHAR2(200),
    data_cadastro DATE DEFAULT SYSDATE
);

INSERT INTO cliente_uuid_v4 (nome, email) VALUES ('Pedro Alves', 'pedro@email.com');
INSERT INTO cliente_uuid_v4 (nome, email) VALUES ('Carla Mendes', 'carla@email.com');

-- Converter RAW(16) para string UUID legivel
SELECT LOWER(REGEXP_REPLACE(RAWTOHEX(cliente_id),
       '(.{8})(.{4})(.{4})(.{4})(.{12})', '\1-\2-\3-\4-\5')) AS uuid_formatado,
       nome, email
  FROM cliente_uuid_v4;

-- ============================================================
-- PARTE 4: UUID V7 (gerado via aplicacao, armazenado como RAW(16))
-- ============================================================

CREATE TABLE cliente_uuid_v7 (
    cliente_id   RAW(16) PRIMARY KEY,
    nome         VARCHAR2(200) NOT NULL,
    email        VARCHAR2(200),
    data_cadastro DATE DEFAULT SYSDATE
);

-- Inserir UUID v7 gerado pela aplicacao
-- Exemplo com Python (oracledb):
--   uid = uuid_v7()
--   cursor.execute(
--       "INSERT INTO cliente_uuid_v7 VALUES (:1, :2, :3, :4)",
--       [uid.bytes, "Nome", "email@ex.com", date.today()]
--   )

-- Exemplo com Java (JDBC):
--   UUID uuid = UuidV7Generator.generateV7();
--   ByteBuffer bb = ByteBuffer.wrap(new byte[16]);
--   bb.putLong(uuid.getMostSignificantBits());
--   bb.putLong(uuid.getLeastSignificantBits());
--   pstmt.setBytes(1, bb.array());

-- ============================================================
-- PARTE 5: COMPARACAO DE TAMANHO DE INDICES
-- ============================================================

-- Consultar tamanho dos indices
SELECT index_name, table_name,
       ROUND(bytes / 1024, 2) AS tamanho_kb
  FROM user_segments
 WHERE segment_name IN (
       SELECT index_name FROM user_indexes
        WHERE table_name IN ('CLIENTE_SEQ', 'CLIENTE_UUID_V4', 'CLIENTE_UUID_V7'))
 ORDER BY bytes DESC;
