@startuml
' BD-13-OrdemLogicaSelect.puml
' Visualizar em: https://plantuml.com/

start
:FROM: origem das linhas;
:WHERE: filtra linhas;
:GROUP BY: agrupa;
:HAVING: filtra grupos;
:SELECT: projeta colunas;
:ORDER BY: ordena o resultado;
stop
@enduml
